apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    app: web
    env: prod
spec:
  schedulerName: my-scheduler
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  labels:
    app: web
    env: prod
spec:
  schedulerName: my-scheduler
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-3
  labels:
    app: web
    env: prod
spec:
  schedulerName: my-scheduler
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-4
  labels:
    app: web
    env: prod
spec:
  schedulerName: my-scheduler
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
